name: Scala CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache SBT dependencies
      uses: actions/cache@v3
      with:
        path: ~/.ivy2/cache
        key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
        restore-keys: |
          ${{ runner.os }}-sbt-

    - name: Cache SBT launcher
      uses: actions/cache@v3
      with:
        path: ~/.sbt
        key: ${{ runner.os }}-sbt-launcher

    - name: Run tests
      run: sbt test

    - name: Generate code coverage
      run: sbt coverage test coverageReport

    - name: Upload coverage to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      run: sbt coveralls
