name: Scala CI
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'adopt'

    - name: Check if sbt is installed and its location
      run: which sbt || echo "sbt is not installed"

    - name: Check sbt version
      run: sbt --version  # This verifies that sbt is installed and available

    - name: compile
      run: sbt compile
      
    - name: Run tests
      run: sbt test
      
  run_test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Build Project and export Coverage
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          echo "Current directory: $(pwd)"
          ls -R
           export CI_BRANCH="${GITHUB_REF#refs/heads/}"
           sbt clean coverage test
           sbt coverageReport coveralls
